language: ruby
#rvm: ## .ruby-version exists
#  - 2.2
script:
  - bundle exec jekyll build
  - bundle exec htmlproof ./_site --url-ignore /linkedin\.com/
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
