language: ruby

cache:
  bundler: true

env:
  global:
    - JEKYLL_ENV=production
    # speeds up installation of html-proofer
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

addons:
  apt:
    packages:
      # required to avoid SSL errors
      - ca-certificates
      - libcurl4-openssl-dev

script:
  - bundle install
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --url-ignore /linkedin\.com/
