language: ruby

env:
  global:
    - JEKYLL_ENV=production
    # speeds up installation of html-proofer
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

addons:
  apt:
    packages:
      # required to avoid SSL errors
      - ca-certificates
      - libcurl4-openssl-dev

cache:
  bundler: true
  directories:
    - $TRAVIS_BUILD_DIR/tmp/.htmlproofer

jobs:
  include:
    - stage: "Bundle Install"
      script: bundle install

    - stage: "Jekyll Build"
      script: bundle exec jekyll build

    - stage: "Lint Ruby Files"
      script: bundle exec rake linter:ruby

    - stage: "Lint YAML Files"
      script: bundle exec rake linter:yaml

    - stage: "Lint Markdown Files"
      script: bundle exec rake linter:markdown

    - stage: "Run HTML Proofer Local"
      script: bundle exec rake proofer:local

    - stage: "Run HTML Proofer Remote"
      script: bundle exec rake proofer:remote
