language: ruby

sudo: required

services:
  - docker

env:
  global:
    - JEKYLL_ENV=production
    - REPO=morazow/blog.morazow.com
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

addons:
  apt:
    packages:
      - ca-certificates
      - libcurl4-openssl-dev

cache:
  bundler: true
  directories:
    - "$TRAVIS_BUILD_DIR/tmp/.htmlproofer"

jobs:
  include:
    - stage: "Build, Lint and Run HTML Proofer"
      script:
        - bundle exec jekyll build
        - bundle exec rake linter:ruby
        - bundle exec rake linter:yaml
        - bundle exec rake linter:markdown
        - bundle exec rake proofer:local
        - bundle exec rake proofer:remote

    - stage: "Deploy Docker Image To DockerHub"
      script:
        - make clean
        - export TAG=$(git describe)
        - echo "Current TAG = $TAG"
        - bundle exec jekyll build
        - cp -r _site docker/nginx/html
        - docker build -t $REPO:$TAG ./docker/nginx/
        - docker tag $REPO:$TAG $REPO:latest
      env:
        - secure: ENbGDE10Je9ByBJmajrT//Txx4eeytTGTJGploss/kJhKjb0o4sB/39d3DmD4KXuo1kbUbUVYy5gJ4ZPPhLkQvAyohen2zD1BR1oJ+W+ekQuNCtQFzB9vUguBXFYWOd2xfyyXk7Xu5IZ7r0CXJ8sRlXCMGjHCt3TeV5BbutA5aL6yYbVdUitDfCtecssM/KfTT4sZ4SwX6/yW6MZZDOhEhGEZWNNz0Ofh6I6HTnplYCwJPASrs4SD8YbVt/+yCOiq5YTUJdzPwSJ6qTDBhslMEpMWzILZTvNyKihJwA1DNrvnGoZewmRXiX+KdLppVOJOqj4QGznJjX5lgBXiysZm+dlrnsE+RWHvs3u74/HnCxVYGRB1G3Pv+SyURaDCHa6Q4/5rKItrkYE6WKhkjniaIYFQOGP6GTWOHuZH6NY787UzSUmJh61kiAhoLuSObo13oYWZaE1f6PoOCIymMtFcEm1HZER3wJlu8ubnJUTeHfxsUvIks9+8vidHAup6WEQ5KExIEi5M+q4zGXU4vN7mm7MRWzhPSl06oKNhxS3rkMhl7uhELkKPlmMs7WJad7AySZH7elWW1VgVmONnCsMpVEByfif/Wb+ETKMDhiYLk4YYXOgn260oUBfhfsyQnYrAFasqsJyS/YxdLTnJnorXhqBkHTiYkYqMdYw7GVJ52U=
        - secure: nzan70jHiBDfxCXl1TSl3rrczwzkPQ8ygRaKezohnzGVR8qnP91I5SFJLWgSV6rlsooDDZjF5CitjgFDI/N+C46m8E+4M/AoSZhkyLBexe2QP/BTYaFqNaGRlU9gEZxxM81eA61qkB6wOxDPHYuBUyHwx/Lm0xACShvsHk2EWukyvpEmRlgkZU4MAJz8Sqx14kP3i9LskrhmBt6v74BLBl5pz0BkkJJ6Iz4UCG87qbeI7oXEEui/FE/x0Z80sIdqhJXpeO0gIMuvlDGhbJfv+KZuTlgprmFnjmZwCn1EF1p5J9mzfhCgMfy0tMQQK0hBGso9/lMJow1EaBlw2NxM66N66FbjnlCj4y4aZkVn+ENN7D7ZOSa/PmF+EQcgrQvU/8uIf4cfoURUYYkYxjkSQNFlouWGviA8CNnODLgNrW2s5m2snUy8XWe95b93mbrc2Bpi+nLL87KozR7Gxu6IW/sImnnqRopHYik6LXS/w1BLD9DJM3x3MmdrXzb19fNHcnNIeuj+WVS1SkBxBBMoBP7boy2A/DXF7y9QQaCj7LvBO3PJD5Z4VyLup25mx/pLlQzotCfrA/zqyMiBPEIVs5PoM6vERKbVxs1B5VC2Iy9OsWU1mT8hyr/a3VabIYiCxs0Gmoul3ETvGsP0IsVeenXwnjMiZ5T+W2HI1+07wtI=
      before_deploy:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      deploy:
        provider: script
        skip_cleanup: true
        script: docker push $REPO:$TAG;
                docker push $REPO:latest;
                docker images
        on:
          branch: master
