language: ruby

sudo: required

services:
  - docker

env:
  global:
    - JEKYLL_ENV=production
    - REPO=morazow/blog.morazow.com
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

addons:
  apt:
    packages:
      # required to avoid SSL errors
      - ca-certificates
      - libcurl4-openssl-dev

cache:
  bundler: true
  directories:
    - $TRAVIS_BUILD_DIR/tmp/.htmlproofer

jobs:
  include:
    - stage: "Build, Lint and Run HTML Proofer"
      script:
        - bundle exec jekyll build
        - bundle exec rake linter:ruby
        - bundle exec rake linter:yaml
        - bundle exec rake linter:markdown
        - bundle exec rake proofer:local
        - bundle exec rake proofer:remote

    - stage: "Deploy Docker Image To DockerHub"
      script:
        - make clean
        - export TAG=$(git describe)
        - echo "Current TAG = $TAG"
        - bundle exec jekyll build
        - cp -r _site docker/nginx/html
        - docker build -t $REPO:$TAG ./docker/nginx/
        - docker tag $REPO:$TAG $REPO:latest
      before_deploy:
        - echo "Before Deploy: Login to docker"
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - echo "Deploying"
          - docker images
        on:
          all_branches: true
