name: SCALED VOID
author: muhammet orazov
url: http://morazow.com
highlighter: pygments
markdown: kramdown
permalink: /blog/:title.html
google_analytics_code: UA-32783435-1
gems:
  - jekyll-sitemap
exclude: [vendor]
