---

url: https://blog.morazow.com

permalink: /blog/:title.html

highlighter: rouge
markdown: kramdown

# Assets
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir: _sass
  style: :compressed

plugins:
  - jekyll-sitemap

exclude:
  - .gitignore
  - .editorconfig
  - .travis.yml
  - .ruby-version
  - README.md
  - LICENSE.md
  - Makefile
  - Rakefile
  - Dockerfile
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - docker
  - vendor
