---
title: SCALED VOID
theme: jekyll-whiteglass
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap

highlighter: rouge
markdown: kramdown

permalink: /:year/:month/:day/:title/
paginate_path: /posts/:num/
paginate: 5

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: category_archives
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

exclude:
  - .gitignore
  - .github
  - README.md
  - LICENSE.md
  - Gemfile
  - Gemfile.lock
  - vendor
