---

url: https://blog.morazow.com

highlighter: rouge
markdown: kramdown
permalink: /blog/:title.html

plugins:
  - jekyll-sitemap

exclude:
  - .gitignore
  - .editorconfig
  - .travis.yml
  - .ruby-version
  - README.md
  - LICENSE.md
  - Makefile
  - Rakefile
  - Dockerfile
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - docker
  - vendor
