version: "3"

services:

  blog:
    build:
      context: .
      dockerfile: ./docker/jekyll/Dockerfile
    image: morazow/blog-dev
    container_name: blog
    volumes:
      - ./:/tmp/blog
    ports:
      - 4000:4000
    environment:
      - JEKYLL_ENV=development
    command: jekyll serve --livereload --future --force_polling --host 0.0.0.0
