name: Broken Links Checker

on:
  schedule:
    - cron: "0 5 * * 0"
  push:
    branches:
      - main
  pull_request:

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - name: Configure broken links checker
        run: |
          echo '{"aliveStatusCodes": [429, 200], "ignorePatterns": []}' > ./links-checker.json
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          config-file: ./links-checker.json
